### ISSUE TITLE
The plugin doesn't work textroom

### ISSUE THREAD

**Issue by alokazay** [RSATom/janus-gateway-snap#1]
web error:  No such plugin 'janus.plugin.textroom'
logs:
Loading plugin 'libjanus_textroom.so'...
[WARN] Data channels support not compiled, disabling TextRoom plugin
[WARN] The 'janus.plugin.textroom' plugin could not be initialized

**Comment by RSATom** [comment]
It looks like I have to add usrsctp library to snap build... Thanks!

**Comment by RSATom** [comment]
@alokazay Can you please check latest `edge` version if this issue is fixed.

**Comment by alokazay** [comment]
Yes! Thx issue was fixed!
