### ISSUE TITLE
AES-GCM support

### ISSUE THREAD

**Issue by wjl0814** [RSATom/janus-gateway-snap#12]
Is there any way via snap or your implementation to support AES-GCM?

![Snipaste_2020-08-23_13-59-13](https://user-images.githubusercontent.com/24514669/90972139-225b3f00-e549-11ea-8cf5-9168b36a2c35.png)

**Comment by RSATom** [comment]
@wjl0814 I've enabled AES-GCM support on `edge` channel. Please test.
