### ISSUE TITLE
"proper" way to add plugins?

### ISSUE THREAD

**Issue by kylebakerio** [RSATom/janus-gateway-snap#13]
From the logs I see that `/opt/janus/lib/janus/plugins` is the plugin folder, ~~but that folder is 'read only'. Should I manually modify permissions on it so that I can copy a plugin into it?~~ doesn't exist, I at a glance thought it was saying what I expected, which was `/snap/janus-gateway/current/opt/janus/etc/janus/`. So, is snap is creating a virtual directory...??? I feel like I'm missing something.

Or is there some other preferred method, like adding some second folder and pointing to it from config?

Or, I also see all the plugins listed in `/var/snap/janus-gateway/common/etc/`, which confuses me... Adding stuff there doesn't work, so it seems that while there's a copy there, that file isn't checked by Janus... Anyways, maybe I should just add it there and modify config to point there now?

**Comment by kylebakerio** [comment]
Well, there could be potential in theory, but I also think they're moving away from Janus and towards mediasoup, but that's as of a couple weeks ago

Networked-aframe already has a plugin and client adapter that go with it. Its plugin is based on the videoroom plugin, but is expanded and customized for NAF-specific features. It isn't feasible to rewrite that functionality at this time.

Also, I think that plugin may be written for the old plugin API, so I may have to use Janus 9.5, if I'm not mistaken, unfortunately.

Looks like I'll try building from source again and give it one last try digging in that direction... I was pretty disappointed to write a very careful and clear question on the Janus support google group and get zero responses, though.

**Comment by RSATom** [comment]
I think the question was answered...
