### ISSUE TITLE
Cant edit config file?

### ISSUE THREAD

**Issue by jrj2211** [RSATom/janus-gateway-snap#15]
I'm trying to disable cors to allow for any device to connect to my janus server. I've been editing the config file in /var/snap/janus-gateway/common/etc/janus.transport.http.jcfg but I'm not seeing my changes being reflected.

For example, as a basic test I'm trying to just change the port its listening on. In the general section of the transport.http config I'm changing:

```
general: {
    port = 8083
}
```

I then restart the snap but the port doesnt change:
- snap restart janus-gateway
- systemctl restart snap.janus-gateway.janus-gateway.service
- Reboot entire server

I get the message saying "Restarted." Checking the logs however it still shows the default port 8088:

> WebSockets server started (port 8188)...

I'm on a fresh install of Debian 10. Only thing I've configured on it was following the snapd instructions to install the janus-gateway snap. Am I doing something wrong?

There are references in the instructions to $SNAP and $SNAP_COMMON but both of those for me are blank, not sure if that has anything to do with it.

**Comment by jrj2211** [comment]
Ideally I'm trying to edit the CORS section in transport.http to allow all origins:

cors: {
  allow_origin = "*"
  enforce_cors = false
}

**Comment by RSATom** [comment]
If you change HTTP config, why did you look to WebSockets related log messages?

**Comment by jrj2211** [comment]
Oops, sorry I copied the wrong line. Heres the log where it shows HTTP port:

> HTTP webserver started (port 8088, /janus path listener)...

**Comment by RSATom** [comment]
1. `/var/snap/janus-gateway/common/etc/janus.transport.http.jcfg` is right path to HTTP config
2. `sudo snap restart janus-gateway` is right way to restart snap

So on first look you did all right way. The only reason I can imagine - you just didn't save your changes to config. Please double check it. And FYI, you have to use `sudoedit` for configs edit.

**Comment by jrj2211** [comment]
Hey, thanks for the tip on sudoedit! Using that I'm getting I was able to get the port to switch and my other config changes are taking effect
