### ISSUE TITLE
Janus-gateway does not start on raspberrypi 4 Buster

### ISSUE THREAD

**Issue by NeGameOnline** [RSATom/janus-gateway-snap#16]
Raspberrypi 4 Buster
Linux raspberrypi 5.10.63-v7l+ #1496 SMP Wed Dec 1 15:58:56 GMT 2021 armv7l GNU/Linux

ERROR
2021-12-15T15:56:30Z janus-gateway.janus-gateway[3045]: [ERR] [plugins/janus_streaming.c:janus_streaming_init:1602] Unable to acquire list of network devices/interfaces; some configurations may not work as expected... 1 (Operation not permitted)
2021-12-15T15:56:30Z janus-gateway.janus-gateway[3045]: [FATAL] [transports/janus_http.c:janus_http_init:795] Couldn't start webserver on port 8088...
2021-12-15T15:56:30Z janus-gateway.janus-gateway[3045]: [FATAL] [transports/janus_http.c:janus_http_init:843] Couldn't start secure webserver on port 8089...
2021-12-15T15:56:30Z janus-gateway.janus-gateway[3045]: [WARN] No HTTP/HTTPS server started, giving up...
2021-12-15T15:56:30Z janus-gateway.janus-gateway[3045]: [WARN] The 'janus.transport.http' plugin could not be initialized

What should I do with the network interface?

**Comment by RSATom** [comment]
Did you follow https://snapcraft.io/docs/installing-snap-on-debian ?

**Comment by RSATom** [comment]
The more important things there are:sudo snap install coreandsnap refresh core15 дек. 2021 г. 23:21 пользователь NeGameOnline ***@***.***> написал:
Yes.
sudo apt -y install snapd

**Comment by NeGameOnline** [comment]
![image](https://user-images.githubusercontent.com/89255600/146361656-e5e87adb-7f45-46dc-a96c-5a15f295f140.png)

**Comment by RSATom** [comment]
Try restart snap with `sudo snap restart janus-gateway` and check if it running correctly. I did fresh install on my RPi 2 and snap started working right after `sudo snap install core`. Unfortunately I don't have RPi 4 and can't check it there.

**Comment by NeGameOnline** [comment]
After `sudo snap restart janus-gateway` shows exactly the same error.

I redeployed the "**Buster**" image from the "Raspberry Pi Imager".
Installed `snap`, then installed `janus-gateway` and got exactly the same error in log:
[ERR] [plugins/janus_streaming.c:janus_streaming_init:1602] Unable to acquire list of network devices/interfaces; some configurations may not work as expected... 1 (Operation not permitted)

OK, then I redeployed the "**Bullseye**" image from the "Raspberry Pi Imager".
Installed `snap`, then installed `janus-gateway`  and janus-gateway starts up and works great!

The problem is reproduced every time only on "**Buster**"
But for my project I need Buster... :(

**Comment by NeGameOnline** [comment]
![image](https://user-images.githubusercontent.com/89255600/146390205-560a42a9-b261-4dff-b4e4-5fed524096a0.png)

**Comment by RSATom** [comment]
Did you do `sudo snap install core` and `sudo snap refresh core` after fresh install of Buster? Without it I was not able run `janus-gateway` too. And I've used https://downloads.raspberrypi.org/raspios_oldstable_lite_armhf/images/raspios_oldstable_lite_armhf-2021-12-02/2021-12-02-raspios-buster-armhf-lite.zip to test on my RPi 2.

**Comment by NeGameOnline** [comment]
I lost the letter d
`sudo apt -y install snap `
should be
`sudo apt -y install snapd`

works properly!
Thanks 👍
