### ISSUE TITLE
janus-gateway 1.0.1 snap build

### ISSUE THREAD

**Issue by mattimo** [RSATom/janus-gateway-snap#19]
It seems that janus-gateway 1.0.1 was been released a while back already, is it possible to provide an updated build?

Is there any way that I can help? If I understand this correctly, it would require creating a branch with a specific name which AFAIK can not be done using a pull-request.

**Comment by RSATom** [comment]
I'll do it soon. Thanks for notify.

**Comment by RSATom** [comment]
Builds for v1.0.1 and v0.12.1 should be available within hour or so...

**Comment by RSATom** [comment]
It's available
