### ISSUE TITLE
record not working

### ISSUE THREAD

**Issue by alokazay** [RSATom/janus-gateway-snap#2]
I made an attempt to write, but the directory is empty.

Ctreate room
`{
                                                "request": "create",
                                                "room": myroom,
                                                "admin_key": 'supersecret',
                                                "permanent": false,
                                                "max_publishers": 6,
                                                "bitrate": 256000,
                                                "fir_freq": 10,
                                                "videocodec": "vp8",
                                                "description": "test",
                                                "secret": "test",
                                                "record ": true,
                                                "rec_dir ": '/var/snap/janus-gateway/common/share/recordings',
                                                "is_private": true 
                                            }`

**Comment by alokazay** [comment]
But janus.plugin.recordplay work

**Comment by RSATom** [comment]
Did you see something in Janus logs?
`sudo snap logs janus-gateway`

**Comment by alokazay** [comment]
2020-04-16T12:33:16Z janus-gateway.janus-gateway[28731]: [1381073083038931] The DTLS handshake has been completed
2020-04-16T12:33:16Z janus-gateway.janus-gateway[28731]: [janus.plugin.videoroom-0x7fa720015230] WebRTC media is now available
2020-04-16T12:33:16Z janus-gateway.janus-gateway[28731]: [5312427871340717] Creating ICE agent (ICE Full mode, controlled)
2020-04-16T12:33:17Z janus-gateway.janus-gateway[28731]: [WARN] [5312427871340717]     Missing valid SRTP session (packet arrived too early?), skipping...
2020-04-16T12:33:17Z janus-gateway.janus-gateway[28731]: [5312427871340717] The DTLS handshake has been completed
2020-04-16T12:33:17Z janus-gateway.janus-gateway[28731]: [janus.plugin.videoroom-0x7fa720007010] WebRTC media is now available
2020-04-16T12:33:17Z janus-gateway.janus-gateway[28731]: Creating new handle in session 2426875550257791: 7028812525254825; 0x7fa760002610 0x7fa76000b010
2020-04-16T12:33:17Z janus-gateway.janus-gateway[28731]: [7028812525254825] Creating ICE agent (ICE Full mode, controlling)
2020-04-16T12:33:18Z janus-gateway.janus-gateway[28731]: [7028812525254825] The DTLS handshake has been completed
2020-04-16T12:33:18Z janus-gateway.janus-gateway[28731]: [janus.plugin.videoroom-0x7fa72006b930] WebRTC media is now available

**Comment by RSATom** [comment]
Don't see any issue in this logs... Did you try configure videoroom with config file (just to test)?

**Comment by RSATom** [comment]
Also, can you try use `/opt/janus/share/janus/recordings` in `rec_dir` option?

**Comment by alokazay** [comment]
Checking command line arguments...
Debug/log level is 4
Debug/log timestamps are enabled
Debug/log colors are disabled
[Thu Apr 16 14:56:24 2020] Adding 'vmnet' to the ICE ignore list...
[Thu Apr 16 14:56:24 2020] Using 88.198.38.237 as local IP...
[Thu Apr 16 14:56:24 2020] [WARN] Token based authentication disabled
[Thu Apr 16 14:56:24 2020] Initializing recorder code
[Thu Apr 16 14:56:24 2020] Initializing ICE stuff (Full mode, ICE-TCP candidates disabled, half-trickle, IPv6 support disabled)
[Thu Apr 16 14:56:24 2020] TURN REST API backend: (disabled)
[Thu Apr 16 14:56:24 2020] Crypto: OpenSSL >= 1.1.0
[Thu Apr 16 14:56:24 2020] [WARN] The libsrtp installation does not support AES-GCM profiles
[Thu Apr 16 14:56:24 2020] [WARN] No cert/key specified, autogenerating some...
[Thu Apr 16 14:56:24 2020] Fingerprint of our certificate: 63:23:E7:F3:4C:4F:95:51:36:87:48:62:1B:08:1B:05:29:94:36:50:2B:15:F6:DB:DD:5E:30:BF:0C:37:E2:C3
[Thu Apr 16 14:56:24 2020] [WARN] Event handlers support disabled
[Thu Apr 16 14:56:24 2020] Plugins folder: /opt/janus/lib/janus/plugins
[Thu Apr 16 14:56:24 2020] Joining Janus requests handler thread
[Thu Apr 16 14:56:24 2020] Sessions watchdog started
[Thu Apr 16 14:56:24 2020] Loading plugin 'libjanus_audiobridge.so'...
[Thu Apr 16 14:56:24 2020] JANUS AudioBridge plugin initialized!
[Thu Apr 16 14:56:24 2020] Loading plugin 'libjanus_echotest.so'...
[Thu Apr 16 14:56:24 2020] JANUS EchoTest plugin initialized!
[Thu Apr 16 14:56:24 2020] Loading plugin 'libjanus_nosip.so'...
[Thu Apr 16 14:56:24 2020] JANUS NoSIP plugin initialized!
[Thu Apr 16 14:56:24 2020] Loading plugin 'libjanus_recordplay.so'...
[Thu Apr 16 14:56:24 2020] JANUS Record&Play plugin initialized!
[Thu Apr 16 14:56:24 2020] Loading plugin 'libjanus_sip.so'...
[Thu Apr 16 14:56:24 2020] JANUS SIP plugin initialized!
[Thu Apr 16 14:56:24 2020] Loading plugin 'libjanus_streaming.so'...
[Thu Apr 16 14:56:24 2020] JANUS Streaming plugin initialized!
[Thu Apr 16 14:56:24 2020] Loading plugin 'libjanus_textroom.so'...
[Thu Apr 16 14:56:24 2020] JANUS TextRoom plugin initialized!
[Thu Apr 16 14:56:24 2020] Loading plugin 'libjanus_videocall.so'...
[Thu Apr 16 14:56:24 2020] JANUS VideoCall plugin initialized!
[Thu Apr 16 14:56:24 2020] Loading plugin 'libjanus_videoroom.so'...
[Thu Apr 16 14:56:24 2020] VideoRoom will use alphanumeric IDs, not numeric
[Thu Apr 16 14:56:24 2020] JANUS VideoRoom plugin initialized!
[Thu Apr 16 14:56:24 2020] Loading plugin 'libjanus_voicemail.so'...
[Thu Apr 16 14:56:24 2020] JANUS VoiceMail plugin initialized!
[Thu Apr 16 14:56:24 2020] Transport plugins folder: /opt/janus/lib/janus/transports
[Thu Apr 16 14:56:24 2020] Loading transport plugin 'libjanus_http.so'...
[Thu Apr 16 14:56:24 2020] HTTP transport timer started
[Thu Apr 16 14:56:24 2020] HTTP webserver started (port 8088, /janus path listener)...
[Thu Apr 16 14:56:24 2020] [WARN] HTTPS webserver disabled
[Thu Apr 16 14:56:24 2020] [WARN] Admin/monitor HTTP webserver disabled
[Thu Apr 16 14:56:24 2020] [WARN] Admin/monitor HTTPS webserver disabled
[Thu Apr 16 14:56:24 2020] JANUS REST (HTTP/HTTPS) transport plugin initialized!
[Thu Apr 16 14:56:24 2020] Loading transport plugin 'libjanus_pfunix.so'...
[Thu Apr 16 14:56:24 2020] [WARN] Unix Sockets server disabled (Janus API)
[Thu Apr 16 14:56:24 2020] [WARN] Unix Sockets server disabled (Admin API)
[Thu Apr 16 14:56:24 2020] [WARN] No Unix Sockets server started, giving up...
[Thu Apr 16 14:56:24 2020] [WARN] The 'janus.transport.pfunix' plugin could not be initialized
[Thu Apr 16 14:56:24 2020] Loading transport plugin 'libjanus_websockets.so'...
[Thu Apr 16 14:56:24 2020] [WARN] libwebsockets has been built without IPv6 support, will bind to IPv4 only
[Thu Apr 16 14:56:24 2020] libwebsockets logging: 0
[Thu Apr 16 14:56:24 2020] WebSockets server started (port 8188)...
[Thu Apr 16 14:56:24 2020] [WARN] Secure WebSockets server disabled
[Thu Apr 16 14:56:24 2020] [WARN] Admin WebSockets server disabled
[Thu Apr 16 14:56:24 2020] [WARN] Secure Admin WebSockets server disabled
[Thu Apr 16 14:56:24 2020] JANUS WebSockets transport plugin initialized!
[Thu Apr 16 14:56:24 2020] WebSockets thread started
[Thu Apr 16 14:56:30 2020] Creating new session: 241927204400571; 0x7fe728001320
[Thu Apr 16 14:56:30 2020] Creating new handle in session 241927204400571: 3112795199310401; 0x7fe728001320 0x7fe728001b00
[Thu Apr 16 14:56:34 2020] [3112795199310401] Creating ICE agent (ICE Full mode, controlled)
[Thu Apr 16 14:56:35 2020] [WARN] [3112795199310401]     Missing valid SRTP session (packet arrived too early?), skipping...
[Thu Apr 16 14:56:35 2020] [3112795199310401] The DTLS handshake has been completed
[Thu Apr 16 14:56:35 2020] [janus.plugin.videoroom-0x7fe6e4008f40] WebRTC media is now available
[Thu Apr 16 14:56:41 2020] Creating new session: 3262241654339036; 0x7fe728003800
[Thu Apr 16 14:56:41 2020] Creating new handle in session 3262241654339036: 2412018235220281; 0x7fe728003800 0x7fe728005320
[Thu Apr 16 14:56:45 2020] Creating new handle in session 3262241654339036: 6850956583941106; 0x7fe728003800 0x7fe7280062c0
[Thu Apr 16 14:56:46 2020] [WARN] [2412018235220281] No stream, queueing this trickle as it got here before the SDP...
[Thu Apr 16 14:56:46 2020] [2412018235220281] Creating ICE agent (ICE Full mode, controlled)
[Thu Apr 16 14:56:46 2020] [ERR] [sdp-utils.c:janus_sdp_get_codec_rtpmap:779] Unsupported codec 'none'
[Thu Apr 16 14:56:46 2020] [6850956583941106] Creating ICE agent (ICE Full mode, controlling)
[Thu Apr 16 14:56:46 2020] [2412018235220281] The DTLS handshake has been completed
[Thu Apr 16 14:56:46 2020] [janus.plugin.videoroom-0x7fe6e400cd60] WebRTC media is now available
[Thu Apr 16 14:56:46 2020] [WARN] [6850956583941106]     Missing valid SRTP session (packet arrived too early?), skipping...
[Thu Apr 16 14:56:46 2020] [6850956583941106] The DTLS handshake has been completed
[Thu Apr 16 14:56:46 2020] [janus.plugin.videoroom-0x7fe6e402aef0] WebRTC media is now available
[Thu Apr 16 14:56:46 2020] Creating new handle in session 241927204400571: 3091949640647428; 0x7fe728001320 0x7fe728006ac0
[Thu Apr 16 14:56:46 2020] [3091949640647428] Creating ICE agent (ICE Full mode, controlling)
[Thu Apr 16 14:56:50 2020] [3091949640647428] The DTLS handshake has been completed
[Thu Apr 16 14:56:50 2020] [janus.plugin.videoroom-0x7fe6e4028b90] WebRTC media is now available

**Comment by alokazay** [comment]
Maybe this [Thu Apr 16 14:56:46 2020] [ERR] [sdp-utils.c:janus_sdp_get_codec_rtpmap:779] Unsupported codec 'none'  ?

Yes my path 

   "videocodec": "vp9,vp8,h264",
                                                            "description": "test",
                                                            "secret": "test",
                                                            "record ": true,
                                                            "rec_dir ": '/var/snap/janus-gateway/common/share/recordings',

**Comment by alokazay** [comment]
Everything is great! This is my mistake! I allowed a space in the variable
