### ISSUE TITLE
Installing new Janus plugin (SFU)

### ISSUE THREAD

**Issue by kevinsuwito** [RSATom/janus-gateway-snap#27]
I'm setting up Janus on Redhat 8 and using `snap` seems to be the simplest way, but I wanted to add an SFU plugin into it ([link](https://github.com/networked-aframe/naf-janus-adapter/blob/master/docs/janus-deployment.md))

Long story short I need to add `libjanus_plugin_sfu.so` and `janus.plugin.sfu.cfg` to the plugins and config folder respectively, but `snap` does not allow modifying the folders whatsoever.

Will you consider adding it to the `snap` package or provide me with the workaround for this?

**Comment by RSATom** [comment]
@kevinsuwito I don't plan add any 3rd party plugins to snap. But you can do it yourself. I've already did the same here: https://github.com/RSATom/janus-gstreamer-plugin/tree/master/snap
