### ISSUE TITLE
Snap installation configs -limits

### ISSUE THREAD

**Issue by kinsleykajiva** [RSATom/janus-gateway-snap#28]
So I have been using, this in production and it has been working like a charm and making installation very easy to handle and manage. 

I have noted that one can't enable the installation to use or enable events emissions, I did do the recommended configs but the server does not emit events, as compared to installing using native installations. 

Also pointing the Janus to log to a custom log file, Janus failed or ignores or may cause errors to the app /server itself.

Is there a fix for this?

**Comment by RSATom** [comment]
> I have noted that one can't enable the installation to use or enable events emissions

What do you mean by "enable events emissions"?

> Also pointing the Janus to log to a custom log file, Janus failed or ignores or may cause errors to the app /server itself.

Snap package is running in sandboxed environment, and have access only to limited amount of places. You can look description of SNAP_COMMON, SNAP_DATA, SNAP_USER_COMMON and SNAP_USER_DATA in https://snapcraft.io/docs/environment-variables

**Comment by kinsleykajiva** [comment]
ok that makes sense , i get it now , thank you for this on the limitation  . 

> What do you mean by "enable events emissions"?
This is just saying in janus capturing events failed to work when you use the snap packages
