### ISSUE TITLE
Way to enable only desired plugins?

### ISSUE THREAD

**Issue by refre5h** [RSATom/janus-gateway-snap#29]
This seems to enable all Janus plugins. How can I add configuration parameters to control what plugins to enable?

For example, when we compile manually, we do the following to enable only videoroom and streaming. Is there a way to do these via snap?
```
./configure --prefix=/opt/janus \
--enable-post-processing \
--disable-all-plugins \
--enable-plugin-videoroom \
--enable-plugin-streaming \
--disable-all-transports \
--enable-rest \
--enable-websockets \
--disable-all-handlers
make && make install && make configs
```

Thanks!

**Comment by RSATom** [comment]
@refre5h you can disable unused plugins with `plugins.disable` in `janus.jcfg`:

```
# You can choose which of the available plugins should be
# enabled or not. Use the 'disable' directive to prevent Janus from
# loading one or more plugins: use a comma separated list of plugin file
# names to identify the plugins to disable. By default all available
# plugins are enabled and loaded at startup.
plugins: {
	#disable = "libjanus_echotest.so,libjanus_recordplay.so"
}
```

**Comment by refre5h** [comment]
@RSATom Thanks! I was looking for a way to do it during installation (i.e. not installing unnecessary plugins at all), but modifying the config afterward also works.

**Comment by RSATom** [comment]
@refre5h it's not possible to modify snap package and remove anything from it during install. It's just read-only image.
