### ISSUE TITLE
Files in "demos" folder unwritable

### ISSUE THREAD

**Issue by refre5h** [RSATom/janus-gateway-snap#32]
I used this snap to build the janus-gateway, and am trying to activate the built-in demo pages according to [this](https://facsiaginsa.com/janus/basic-janus-configuration-with-ssl) and [this](https://facsiaginsa.com/janus/enable-janus-admin-monitoring-page) guide which states I'd need to modify some js files in the demos folder, e.g. "admin.js" if I want to activate the admin monitoring page.

However, it doesn't look like any file in `/snap/janus-gateway/current/opt/janus/share/janus/demos` is writable (even with sudo).

![image](https://github.com/RSATom/janus-gateway-snap/assets/7074770/3864dd39-2f79-4222-9a81-36859aef97ac)

The index page works (`https://<mydomain>/index.html`), but I wasn't able to get the "admin" demo working (`https://<mydomain>/admin.html`). Not sure if that's the reason.

Any advice?

**Comment by refre5h** [comment]
Turns out to be nginx setting error. Sorry about that.

**Comment by RSATom** [comment]
@refre5h snap package content is always read-only. If you need to modify it - you have to copy it to some rw place...
