### ISSUE TITLE
What's the path to the janus-gateway log file?

### ISSUE THREAD

**Issue by refre5h** [RSATom/janus-gateway-snap#34]
Using `sudo snap logs janus-gateway -f` can see the logs of janus-gateway. I want to send those logs to somewhere else, so a path to the log file is needed.

I could only find janus-gateway related logs in `/var/log/syslog` which has other unrelated logs as well. Is there a dedicated file that stores only the janus-gateway logs?

**Comment by RSATom** [comment]
You can configure logs output to file with [Janus config](https://github.com/meetecho/janus-gateway/blob/e1c7704cfdef76cd5b177ba7fbb92c041bddd40e/conf/janus.jcfg.sample.in#L16)
The only thing you should take into account snap package can access only to limited list of locations.

**Comment by refre5h** [comment]
Thanks for the tips!
