### ISSUE TITLE
[ERR] [record.c:janus_recorder_create_full:231] fopen error: 24

### ISSUE THREAD

**Issue by refre5h** [RSATom/janus-gateway-snap#35]
This didn't happen when I installed Janus "the default way". But after using this snap, I encountered an error `fopen error: 24` and Janus restarted during a stress test when there were about 120~130 publishers. Recording was enabled.

Is this the infamous "Too many open files" error mentioned in readme?

```
...
[ERR] [record.c:janus_recorder_create_full:231] fopen error: 24
[ERR] [plugins/janus_videoroom.c:janus_videoroom_recorder_create:8392] Couldn't open a video recording file for this publisher!
[ERR] [record.c:janus_recorder_create_full:231] fopen error: 24
[ERR] [plugins/janus_videoroom.c:janus_videoroom_recorder_create:8392] Couldn't open a data recording file for this publisher!
Logger plugins folder: /opt/janus/lib/janus/loggers
[WARN] Couldn't access logger plugins folder...
--------------------------------------------------- Starting Meetecho Janus (WebRTC Server) v1.2.0
---------------------------------------------------
Checking command line arguments...
Debug/log level is 4
...
```

The system already has the max limit configured in `/etc/security/limits.conf`:
```
*      soft     nofile     1048576
*      hard     nofile     1048576
```

Do I also need to set the limit for `snap.janus-gateway.janus-gateway.service`?

p.s. I could've run another test to confirm this, but since stress tests cost $$, I'd like to get a confirmation before another run. Thanks!

**Comment by RSATom** [comment]
> Is this the infamous "Too many open files" error mentioned in readme?

Sorry, I don't know. But it's highly possible.

**Comment by refre5h** [comment]
Just did what the readme says. Confirmed it is indeed the "Too many open files" error. Thanks!

`systemctl edit snap.janus-gateway.janus-gateway.service`
```
[Service]
LimitNOFILE=65536
```
