### ISSUE TITLE
Adding LimitNOFILE=65536 for systemd

### ISSUE THREAD

**Issue by jmordica** [RSATom/janus-gateway-snap#4]
Is there any way via snap or your implementation to add the parameter `LimitNOFILE=65536` to `/etc/systemd/system/snap.janus-gateway.janus-gateway.service` or is this built by snap automatically and can't be altered?

**Comment by RSATom** [comment]
I think this file is generated by snapd on install, or something similar, so don't sure I can change it.

**Comment by jmordica** [comment]
No problem. Closing this. Thanks for the snap!

**Comment by vterdunov** [comment]
I solved it by `systemctl edit snap.janus-gateway.janus-gateway.service`
```
[Service]
LimitNOFILE=65536
```
