### ISSUE TITLE
Need "Data Channels Support"

### ISSUE THREAD

**Issue by gecegezen** [RSATom/janus-gateway-snap#6]
Hello friend,
I'd very much appreciate if you could quickly add "Data Channels Support" compiled in. I came a long way through some server configuration and while nearing the end, top level server software complained about this issue leaving me in a dead-end. 
Thank you.

**Comment by RSATom** [comment]
@gecegezen it should be enabled in `edge` channel, please test.
I don't plan add it to `stable` channel.

**Comment by gecegezen** [comment]
Hello,

I had finally compiled it myself. Then I saw your reply. Actually Edge channel did the work for NextCloud Talk HPB/SFU on CentOS 7. 

For those dealing with Spreed Talk HPB implementation, I am leaving this comment to shine some light on their way. Edge channel will do. 

Cheers.
