### ISSUE TITLE
How to alter ulimit for snap ?

### ISSUE THREAD

**Issue by ujjwal18** [RSATom/janus-gateway-snap#7]
unable to alter ulimit event installing with --classic 
any other way to tweak this setting ?

**Comment by RSATom** [comment]
https://github.com/RSATom/janus-gateway-snap/issues/4
I've already investigated this question, and didn't find any way to do it.

**Comment by vterdunov** [comment]
I solved it by `systemctl edit snap.janus-gateway.janus-gateway.service`

```
[Service]
LimitNOFILE=65536
```

**Comment by RSATom** [comment]
there is no access to .service file from snap itself...

**Comment by RSATom** [comment]
Some maybe useful hints I've found https://forum.snapcraft.io/t/how-to-customize-systemd-service-created-by-snapd/18397/3

**Comment by vterdunov** [comment]
> Some maybe useful hints I've found https://forum.snapcraft.io/t/how-to-customize-systemd-service-created-by-snapd/18397/3

Command above just do it the same thing.

**Comment by vterdunov** [comment]
systemctl edit creates drop-in file.
```
/etc/systemd/system/snap.janus-gateway.janus-gateway.service.d/override.conf
```

man systemctl
> this command creates a drop-in file for each unit either for the system,
           for the calling user, or for all futures logins of all users.

**Comment by RSATom** [comment]
@vterdunov  good to know. :+1:

**Comment by Si-Richards** [comment]
@vterdunov if you have any other performance tweaks please let me know ;-)
I'm guessing nothing needs to be overridden outside the snap in the OS for limits.conf or systmctl.conf ?

**Comment by RSATom** [comment]
Added hint to Readme. @vterdunov thanks!
